
version: '3.8'

networks:
  relayer-demo:
    driver: bridge

services:
  relayer-database:
    build:
      context: database
      dockerfile: Dockerfile
    # image: postgres
    container_name: relayer-database
    # command: >
    #   /usr/config/entrypoint.sh
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
    ports:
    - "5432:5432"
    expose: [5432]
    networks:
      - relayer-demo
  relayer-wss-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: relayer-wss-1
    # depends_on:
    #   - relayer-database
    environment:
      - WSS_NAME=wss-01
      - WSS_PORT=80
      - WSS_ADDRESS=http://relayer-wss-1 # is internal to network
      - WSS_SOCKET_ADDRESS=ws://localhost:8000 # is external and accessible from host
      - DB_USER=postgres
      - DB_PWD=mysecretpassword
      - DB_HOST=relayer-database
      - DB_PORT=5432
    ports:
    - "8000:80"
    networks:
      - relayer-demo
  relayer-wss-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: relayer-wss-2
    # depends_on:
    #   - relayer-database
    environment:
      - WSS_NAME=wss-02
      - WSS_PORT=80
      - WSS_ADDRESS=http://relayer-wss-2 # is internal to network
      - WSS_SOCKET_ADDRESS=ws://localhost:8010 # is external and accessible from host
      - DB_USER=postgres
      - DB_PWD=mysecretpassword
      - DB_HOST=relayer-database
      - DB_PORT=5432
    ports:
    - "8010:80"
    networks:
      - relayer-demo
